name: Docker Image CI

on:
  push:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/eol-uchile/backup_container:${GITHUB_SHA}
        docker build . --file Dockerfile.old --tag ghcr.io/eol-uchile/backup_container:old-${GITHUB_SHA}

    - name: Push to Github Container Registry
      run: |
          echo "${CR_PAT}" | docker login ghcr.io -u eolito --password-stdin
          docker push ghcr.io/eol-uchile/backup_container:${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/backup_container:old-${GITHUB_SHA}
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
