name: Docker Image CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag eoluchile/backup_container:${RELEASE_VERSION}
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      
    - name: Push
      run: |
        echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
        docker push eoluchile/backup_container:${RELEASE_VERSION}
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
