name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/eol-uchile/backup_container:${GITHUB_SHA}

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to Github Container Registry
      if: github.ref == 'refs/heads/master'
      run: |
        docker push ghcr.io/eol-uchile/backup_container:${GITHUB_SHA}
